[package]
name = "arp_scan"
version = "0.1.0"
edition = "2021"

[dependencies]
pnet = "0.34.0"
rand = "0.8.5"
lazy_static = "1.4.0"

[build-dependencies]
# No additional dependencies needed for build.rs